version: '3.7'

services:
  shop_db:
    image: postgis/postgis:latest
    restart: on-failure
    volumes:
    - postgres_data:/var/lib/postgres/data/pgdata
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  django:
    container_name: shop_web
    build: .
    restart: always
    command:  bash -c "python /usr/src/app/manage.py migrate --noinput &&
              python /usr/src/app/manage.py runserver 0.0.0.0:8000"
    volumes:
    - .:/usr/src/app
    ports:
    - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - shop_db
volumes:
  postgres_data: